export enum InnerResponseStatus {
  SUCCESS = 'AUTHENTICATION_SUCCESS',
  LOCKED = 'AUTHENTICATION_LOCKED',
  FAILED = 'FAILED_AUTHENTICATION',
  INIT_FAILED = 'AUTHENTICATION_FAILED',
  CANCELED = 'AUTHENTICATION_CANCELED',
}
