export enum AlgoanEvents {
  ADEN_ANALYSIS_COMPLETED = 'aden_analysis_completed',
  RECOVERY_REQUIRED = 'recovery_required',
  SERVICE_ACCOUNT_CREATED = 'service_account_created',
  SERVICE_ACCOUNT_DELETED = 'service_account_deleted',
  PRODUCTS_REQUIRED = 'products_required',
  PRICINGS_REQUIRED = 'pricings_required',
  INSURANCES_REQUIRED = 'insurances_required',
  DECISION_REQUIRED = 'decision_required',
  LEGAL_DOCUMENT_REQUIRED = 'legal_documents_required',
  KYC_DOCUMENTS_LIST_REQUIRED = 'kyc_documents_list_required',
  BANK_READER_LINK_REQUIRED = 'bankreader_link_required',
  BANK_READER_REQUIRED = 'bankreader_required',
  BANK_READER_COMPLETED = 'bankreader_completed',
  CREDIT_SCORE_REQUIRED = 'credit_score_required',
  CREDIT_SCORE_COMPLETED = 'credit_score_completed',
  FINANCIAL_CHECK_COMPLETED = 'financial_check_completed',
}
