# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - develop
  - qa
  - preprod
  
pool: odb_vmss_agent_pool_dev
stages:
  # ---- BUILD STAGE
  - stage: ConfigPublication
    displayName: build checkmarx package
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.Repository.LocalPath)'
              ArtifactName: '$(Build.BuildNumber)'
              publishLocation: 'Container'