trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - libs/*

pr: none

pool: odb_vmss_agent_pool_dev
variables:
  # Azure service connection established during pipeline creation
  azureSubscription: SUB_ONEY_CO
  serviceConnection: ODB_DEV_CONNECT
  appName: oney
  imageRepository: 'oney'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  # ---- Build, lint and Test stage
  - stage: Publishing
    displayName: Publishing libraries to artifact
    jobs:
      - job: Publish
        displayName: Build and publishing
        steps:
          - checkout: self
            persistCredentials: true
          - script: git reset --hard HEAD && git checkout develop
            displayName: 'checkout on branch'
          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: '14.15.1'
            displayName: 'Install Node'
          - task: npmAuthenticate@0
            inputs:
              workingFile: '$(Build.SourcesDirectory)/.npmrc'
          - script: "npm install -g yarn"
            displayName: "installing yarn"
          - script: "yarn install"
            displayName: "installing dependencies"
          #Linting
          - script: npx nx affected:lint --base=origin/develop
            displayName: 'Run linting'
          #Run unit tests refer to the compare code base affected by changes.
          - script: npx nx affected:test --codeCoverage --base=origin/develop
            displayName: 'Run unit tests'
          - script: |
              git config user.email "you@example.com"
              git config user.name "Your Name"
              git update-index --assume-unchanged .npmrc
              git update-index --assume-unchanged yarn.lock
          #Run publish with lerna and building in postversion script in pkg.json
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run publish:libs --no-git-tag-version'
              publishRegistry: useFeed
              publishFeed: OneyPay
            displayName: 'Publishing packages'
