pr:
  - develop

trigger: none

pool: odb_vmss_agent_pool_dev
variables:
  # Azure service connection established during pipeline creation
  azureSubscription: SUB_ONEY_CO
  serviceConnection: ODB_DEV_CONNECT
  appName: oney
  imageRepository: 'oney'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  targetBranch: $(echo "$(System.PullRequest.TargetBranch)" | awk -F/ '{print $NF}')
  sourceBranch: $(echo "$(System.PullRequest.SourceBranch)" | awk -F/ '{print $NF}')

stages:
  - stage: Build_LinterAndTest
    displayName: Build_LinterAndTest
    jobs:
      - job: InstallDependencies
        steps:
          - template: templates/pr-pipelines-setup-steps-template.yml  # Template reference
      - job: Build
        dependsOn: InstallDependencies
        steps:
          - template: templates/pr-pipelines-setup-steps-template.yml  # Template reference
          #Build
          - script: npx nx affected:build --base=origin/$(targetBranch) --with-deps
            displayName: 'Run affected build'
      - job: Linter
        dependsOn: InstallDependencies
        steps:
          - template: templates/pr-pipelines-setup-steps-template.yml  # Template reference
          #Linting
          - script: npx nx affected:lint --base=origin/$(targetBranch) --parallel
            displayName: 'Run linting'
      - job: Test
        dependsOn: InstallDependencies
        steps:
          - template: templates/pr-pipelines-setup-steps-template.yml  # Template reference
          #Run unit tests e.g base=origin/master refer to the compare code base affected by changes.
          - script: npx nx affected:test --codeCoverage --base=origin/$(targetBranch) --parallel
            displayName: 'Run unit tests'
      - job: Docs
        dependsOn: InstallDependencies
        steps:
          - template: templates/pr-pipelines-setup-steps-template.yml  # Template reference
          - script: yarn docs
            displayName: 'Generate living documentation'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(System.DefaultWorkingDirectory)/docs'
              artifactName: Documentation
