export enum AddressNature {
  MAIN = 'MAIN',
  SHIPPING = 'SHIPPING',
  SECONDARY = 'SECONDARY',
  HOME = 'HOME',
  PROFESSIONAL = 'PROFESSIONAL',
  OTHER = 'OTHER',
  REPAIR = 'REPAIR',
  DESTINATION = 'DESTINATION',
}
