export enum TransactionStatus {
  PENDING = 'PENDING',
  CLEARED = 'CLEARED',
  REFUND = 'REFUND',
  FAILED = 'FAILED',
  WAITING_VALIDATION = 'WAITING_VALIDATION',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
